# Generated by Django 3.0.3 on 2020-07-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_commentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent11',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
